use_frameworks!

platform :ios, '14.0'



target 'RJFloatingLabelTextField_Example' do
 pod 'RJFloatingLabelTextField', '0.1.0'
# , :path => '../'

  target 'RJFloatingLabelTextField_Tests' do
    inherit! :search_paths

    
  end
end
