use_frameworks!

platform :ios, '10.0'



target 'RJFloatingLabelTextField_Example' do
 pod 'RJFloatingLabelTextField', :path => '../'

  target 'RJFloatingLabelTextField_Tests' do
    inherit! :search_paths

    
  end
end
